### ISSUE TITLE
Cannot run the example template

### ISSUE THREAD

**Issue by jslok** [pytorch/live#51]
### Version

0.1.3

### Problem Area

Pytorch Live Template

### Steps to Reproduce

I downloaded the example app with `npx react-native init pytorchlive --template react-native-template-pytorch-live`

When trying to run on my android device, I was getting errors saying it could not find the ptl files. After some research, I need to run models\make_models.py? Then I get this error:

`
C:\Users\jslok\Projects\pytorchlive\models>py make_models.py
torch version 1.11.0+cpu
Exporting image classification models
Exporting model resnet18
Model resnet18 successfully exported
Exporting model mobilenet_v3_small
Traceback (most recent call last):
  File "C:\Users\jslok\Projects\pytorchlive\models\make_models.py", line 124, in <module>
    main()
  File "C:\Users\jslok\Projects\pytorchlive\models\make_models.py", line 117, in main
    export_image_classification_models()
  File "C:\Users\jslok\Projects\pytorchlive\models\make_models.py", line 49, in export_image_classification_models
    bundle_live_spec_and_export_model(name, script_model)
  File "C:\Users\jslok\Projects\pytorchlive\models\make_models.py", line 26, in bundle_live_spec_and_export_model
    optimized_model = optimize_for_mobile(model)
  File "C:\Python310\lib\site-packages\torch\utils\mobile_optimizer.py", line 62, in optimize_for_mobile
    optimized_cpp_module = torch._C._jit_pass_optimize_for_mobile(
RuntimeError: Expected a value of type 'NoneType' for field 'bias', but found 'Tensor'
`
I am on a windows machine.

### Expected Results

Template app should run.

**Comment by t4rf9** [comment]
Same problem met

**Comment by clarksandholtz** [comment]
Looks like @raedle addressed this in [a0a9073](https://github.com/pytorch/live/commit/a0a90738ec12d932bb5c7ca0332eed693124b86b).

Can you confirm if this fixed it for you, @jslok?

**Comment by raedle** [comment]
The issues were addressed in the current released version `0.2.0`. Closing the issue. Please reopen if the issue still happens on your end
